apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermicro2-deployment
spec:
  selector:
    matchLabels:
      app: kubermicro2
  replicas: 3
  template:
    metadata:
      labels:
        app: kubermicro2
    spec:
     containers:
     - name: kubermicro2
       image: darkrastar/kubermicro_2:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080