apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermicro21-deployment
spec:
  selector:
    matchLabels:
      app: kubermicro21
  replicas: 3
  template:
    metadata:
      labels:
        app: kubermicro21
    spec:
     containers:
     - name: kubermicro21
       image: mlexchange/knative-model-deploy
       imagePullPolicy: Always
       ports:
       - containerPort: 8081